"""Shared data models for agent communication."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class AgentType(str, Enum):
    """Available utility agent types."""
    PRODUCT_INFO = "product_info"
    FAQ = "faq"
    KNOWN_OUTAGES = "known_outages"
    SERVICE_INFO = "service_info"
    TICKET_UPDATES = "ticket_updates"
    BILLING = "billing"
    SALES = "sales"
    TECHNICAL_SUPPORT = "technical_support"
    ACCOUNT_ADMIN = "account_admin"


class Priority(str, Enum):
    """Request priority levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class RiskLevel(str, Enum):
    """Security risk levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ExecutionStep(BaseModel):
    """A single step in the execution plan."""
    step_number: int = Field(..., description="Order of execution")
    agent_type: AgentType = Field(..., description="Agent to invoke")
    instruction: str = Field(..., description="Specific instruction for the agent")
    depends_on: list[int] = Field(default_factory=list, description="Steps this depends on")
    reason: str = Field(..., description="Why this agent is needed")


class ExecutionPlan(BaseModel):
    """Execution plan generated by the orchestrator."""
    plan_id: str = Field(..., description="Unique plan identifier")
    customer_id: str = Field(..., description="Customer account ID")
    intent: str = Field(..., description="Original customer intent")
    steps: list[ExecutionStep] = Field(..., description="Ordered execution steps")
    estimated_complexity: str = Field(..., description="low, medium, or high")
    requires_human_review: bool = Field(default=False)
    human_review_reason: str | None = Field(None)


class OrchestratorPayload(BaseModel):
    """Payload received from Lambda invoking the orchestrator."""
    customer_id: str = Field(..., description="Customer account identifier")
    intent: str = Field(..., description="Customer intent/query")
    session_id: str | None = Field(None, description="Session ID for conversation tracking")
    priority: Priority = Field(default=Priority.MEDIUM)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SecurityVerificationRequest(BaseModel):
    """Request sent to external security agent for plan verification."""
    request_id: str = Field(..., description="Unique request identifier")
    customer_id: str = Field(..., description="Customer account ID")
    intent: str = Field(..., description="Original customer intent")
    execution_plan: ExecutionPlan = Field(..., description="Plan to be verified")
    priority: Priority = Field(default=Priority.MEDIUM)
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional context")


class SecurityVerificationResponse(BaseModel):
    """Response from external security agent."""
    request_id: str = Field(..., description="Original request identifier")
    approved: bool = Field(..., description="Whether the plan is approved for execution")
    risk_level: RiskLevel = Field(default=RiskLevel.LOW, description="Risk assessment")
    denial_reason: str | None = Field(None, description="Reason if plan was denied")
    modified_plan: ExecutionPlan | None = Field(None, description="Modified plan if suggested")
    restrictions: list[str] = Field(default_factory=list, description="Restrictions on execution")
    required_audit: bool = Field(default=False, description="Whether execution requires audit logging")
    audit_id: str | None = Field(None, description="Security audit trail ID")


class AgentRequest(BaseModel):
    """Request model for agent invocation."""
    request_id: str = Field(..., description="Unique request identifier")
    query: str = Field(..., description="User query or instruction")
    context: dict[str, Any] = Field(default_factory=dict, description="Additional context")
    customer_id: str | None = Field(None, description="Customer identifier if available")
    session_id: str | None = Field(None, description="Session identifier")
    priority: Priority = Field(default=Priority.MEDIUM, description="Request priority")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentResponse(BaseModel):
    """Response model from agent execution."""
    request_id: str = Field(..., description="Original request identifier")
    agent_type: str = Field(..., description="Agent that processed the request")
    success: bool = Field(..., description="Whether the request was successful")
    response: str = Field(..., description="Agent response text")
    data: dict[str, Any] = Field(default_factory=dict, description="Structured response data")
    tools_used: list[str] = Field(default_factory=list, description="Tools invoked")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score")
    requires_escalation: bool = Field(default=False)
    escalation_reason: str | None = Field(None)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class OrchestratorResponse(BaseModel):
    """Response from the orchestrator."""
    request_id: str
    customer_id: str
    intent: str
    execution_plan: ExecutionPlan
    security_verification: SecurityVerificationResponse | None = Field(
        None, description="Security verification result"
    )
    agent_responses: list[AgentResponse] = Field(default_factory=list)
    final_response: str = Field(..., description="Consolidated response to customer")
    success: bool = True
    blocked_by_security: bool = Field(default=False, description="Whether blocked by security")
    requires_escalation: bool = False
    escalation_reason: str | None = None


class ToolCall(BaseModel):
    """Model for tool invocation via AgentCore Gateway."""
    tool_name: str = Field(..., description="Name of the tool to invoke")
    parameters: dict[str, Any] = Field(default_factory=dict, description="Tool parameters")
    timeout_seconds: int = Field(default=30, description="Timeout for tool execution")


class ToolResult(BaseModel):
    """Result from tool execution."""
    tool_name: str = Field(..., description="Name of the executed tool")
    success: bool = Field(..., description="Whether tool execution succeeded")
    result: dict[str, Any] = Field(default_factory=dict, description="Tool result data")
    error: str | None = Field(None, description="Error message if failed")
    execution_time_ms: int = Field(default=0, description="Execution time in milliseconds")


class CustomerContext(BaseModel):
    """Customer context information."""
    customer_id: str
    account_number: str | None = None
    name: str | None = None
    email: str | None = None
    phone: str | None = None
    account_type: str | None = None
    is_authenticated: bool = False
